---
- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add the docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install the docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce

- name: Add me to the docker group
  user:
    name: jjl25
    append: yes
    groups: docker
